Add Chainstack to 3rd party providers
binance-chain/docs-site pull request #500
Opened 2021-06-19 08:47 UTC by akegaviar

2021-06-21 03:53 UTC, easeev requested changes
Suggestions:
- Order providers in alphabetical order
- Change link for Chainstack to https://chainstack.com/build-better-with-binance-smart-chain/
- Add hyperlink for [Chainstack](https://chainstack.com/)

2021-06-21 04:14 UTC, LeHoang88 approved these changes

2021-06-21 04:14 UTC, LeHoang88 approved these changes

2021-06-21 07:17 UTC, akegaviar commented
> Suggestions

Done

2021-06-21 07:29 UTC, easeev approved these changes
LGTM

2021-06-22 09:42 UTC, huangsuyu approved these changes

2021-06-22 09:42 UTC, merged